### ISSUE TITLE
Foundation 5.5.2

### ISSUE THREAD

**Issue by gitblit** [webjars/foundation#23]
I successfully updated the Bower version but there are missing dependencies that appear unavailable in Bower. (e.g. Modernizr).

**Comment by jamesward** [comment]
Were you not able to deploy a Modernizr Bower WebJar?

**Comment by gitblit** [comment]
Correct.  I didn't try too hard and I've never looked at Bower before last night.  There was no obvious match for Modernizr in the filterable dropdown list of Bower packages.

**Comment by jamesward** [comment]
Hmm... That is odd that it isn't in Bower.
