### ISSUE TITLE
Upgrade to 6.4.3

### ISSUE THREAD

**Issue by sofiageo** [webjars/foundation#34]
Hi, are there any plans to upgrade to 6.4.3 ? It has been released since last August. The current webjar (6.4.2) has an extra css source mapping that create an extra 404 error.

I can see an npm foundation webjar at http://central.maven.org/maven2/org/webjars/npm/foundation-sites/6.4.3/ 

Should I use this one instead? is it also released by you? Thanks!

**Comment by jamesward** [comment]
This will be released shortly.

**Comment by sofiageo** [comment]
Thanks for the update, however, I think you forgot to update the upstream url. This has the effect of downloading the previous version 6.4.2 again.

**Comment by jamesward** [comment]
Oh shoot.  Sorry!  Will fix that and release `6.4.3-1` shortly.
